name: mock_interview_task
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.5
  hooks_riverpod: ^1.0.4
  fluttertoast: ^8.0.9
  equatable: ^2.0.3
  freezed_annotation: ^2.0.3
  flutter_screenutil: ^5.5.3+2
  http: ^0.13.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.11
  freezed: ^2.0.3+1
  json_serializable: ^6.2.0
  flutter_lints: ^2.0.1


flutter:

  uses-material-design: true

  assets:
    - assets/data.json

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
